version: '3.8'

networks:
  mynet: # Réseau existant
    external: true

volumes:
  mysqlvol: # Volume existant
    external: true

services:
  db:
    image: mysql
    container_name: mysqldb-container
    networks:
      - mynet
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysqlvol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  backend:
    image: salmasaghough/backend-app:latest
    container_name: backend-container
    depends_on:
      - db
    networks:
      - mynet
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "9192:9192"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      retries: 5

  frontend:
    image: salmasaghough/frontend-app:latest  
    container_name: frontend-container
    networks:
      - mynet
    ports:
      - "3000:80"
    depends_on:
      - backend
