spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 02069812Salma_
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
  management:
    endpoints:
      web:
        exposure:
          include: health,info  # Exposer l'endpoint /actuator/health et /actuator/info
    endpoint:
      health:
         show-details: always  # Afficher les détails de santé, même si l'application est saine


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      database-platform: org.hibernate.dialect.MySQLDialect
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          use_sql_comments: true
    open-in-view: false # Éviter les fuites de sessions Hibernate

server:
  port: 9192
  address: 0.0.0.0
  ssl:
    enabled: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


