apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: exam
spec:
  minAvailable: 1 # Toujours au moins 1 Pod disponible
  selector:
    matchLabels:
      app: backend 
