apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: exam
spec:
  minAvailable: 2 # Au moins 2 Pods disponibles
  selector:
    matchLabels:
      app: frontend 
