apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: exam
spec:
  hard:
    requests.cpu: "2"        # Maximum de 2 CPU en requests pour tout le namespace
    requests.memory: "4Gi"   # Maximum de 4Gi de mémoire en requests pour tout le namespace
    limits.cpu: "4"          # Maximum de 4 CPU en limits pour tout le namespace
    limits.memory: "8Gi"     # Maximum de 8Gi de mémoire en limits pour tout le namespace
