apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resource-manager-binding
  namespace: exam
subjects:
  - kind: User # Type du sujet (User, Group, ou ServiceAccount)
    name: Salma # Nom de l'utilisateur à qui ce rôle s'applique
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role # Type de rôle (Role ou ClusterRole)
  name: resource-manager # Nom du rôle associé
  apiGroup: rbac.authorization.k8s.io
