apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-standard
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data  # Ajustez ce chemin selon votre environnement
