apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-my-cluster-pxc-db-pxc-1
  namespace: exam
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Ajustez la taille si nécessaire
  storageClassName: manual  # Spécifiez ici votre classe de stockage, si nécessaire
